dist: trusty
language: rust
services: docker
sudo: required
env:
  global:
  - CRATE_NAME=timekeeper
matrix:
  include:
  # Linux Systems.
  - env: TARGET=mips-unknown-linux-gnu
  - env: TARGET=mips-unknown-linux-uclibc
    rust: nightly
  - env: TARGET=x86_64-unknown-linux-gnu
  - env: TARGET=armv7-unknown-linux-gnueabihf
  - env: TARGET=arm-unknown-linux-gnueabihf
before_install:
- set -e
- rustup self update
install:
- sh deployments/install.sh
- source ~/.cargo/env || true
script:
- bash deployments/tests.sh
after_script: set +e
cache: cargo
before_cache:
- chmod -R a+r $HOME/.cargo
branches:
  only:
  - "/^v\\d+\\.\\d+\\.\\d+.*$/"
  - master
notifications:
  email:
    on_sucess: never
    recipients:
    - ruieduardo.fa.lopes@ua.pt
before_deploy:
  - sh deployments/deploy.sh
deploy:
  provider: releases
  api_key:
    secure: QP5SrjgjzPIOfLr6+iMZalC++CXHku5YjFJ0idRIDFiiIaR6ls0HZpUtcWqiOdcMDsvVSTngv1dA8Vg+PNW4z/B9ALV2pPoyIGJizXNDO+YK3TB5Flt4OTjx4ZNp5yVg0+VFcUDcVZgK8GHMfHEuAAwxPWNQgTkOpPmkaDit5Oz3PYPlcqr8y8Q+ntTHizFeoZYoRqP1ztgWswfmyJoqo0Fzu7NG2x0OhBsA5eCJCkxl2Q5YvtKYDS24WJ0Hc+UOT77WIBP6UlumJswvmzNhWnTZYorIfuyDGjKxOti69oEvZfyxNdKPNBZfS/ZrV0umn/K0sxJvmcR/Yz2QI3EqrH21hLQCwvcwkpNt3RRRT8YcYcuBkGL3q6zHz4ikYm5rOgX4rrMbLwtRbZJ94s4qJ0gCbvUrVp/UzGYQZC+UQcwFsy+clZCgjEuUwcnp2E9hxCUBlM4a5LDGexBbb6c3eCnqiwxB0AqU4gxmRkrUIdYk3ep0YHLTvk5YTwAuJoPMhp2D5Ys+CRcwl++AoGkVFV3DrBKwsyNVgj2uJB/WOZy1LZnMc3s4qIHGD+OvFVsQsUAcRJbHbfZ9aqhf7yhod7R9s3ZrQbWDgyAY3PuzPdfNstwxMT+tHAaDL7JxHtYQHm5rwAsbdJVwVp1JbSYUiA7tehR20ibdixWQbTjkjvU=
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  skip_cleanup: true
  on:
    tags: true
    repo: ruieduardolopes/timekeeper
